### ISSUE TITLE
Addons and upgrades should be merged into one type

### ISSUE THREAD

**Issue by UntouchedWagons** [Poenjabiesous/OpenModularTurrets#20]
There's really no difference between addons and upgrades, both alter the turret's behaviour. I suggest that they be combined into one type, the current textures can be kept: red for turret base effects and blue for turret head effects.

I also propose that the addons be polled rather than hard coding an addon to a specific ability, this will allow us and others to add more addons without having to change any of the turret code.

**Comment by Poenjabiesous** [comment]
This cant work anymore, we need to keep them separate.
