### ISSUE TITLE
warning message spam

### ISSUE THREAD

**Issue by AspectMalygos** [Poenjabiesous/OpenModularTurrets#35]
whenever someone enters the 40 block range from a turret hostile to players, their sound and chat is spammed with the warning message. The sound and message play roughly 10 times a second.

I will get any additional information you may require. but some basic info that might help is;
Were playing on my direwolf 1.7.10 1.0.2 server. with a couple of extra mods tossed in.

Loving the mod, but it still has some kinks that need ironing :)

**Comment by Poenjabiesous** [comment]
Fixed in upcoming new release 1.4.1.
