### ISSUE TITLE
Turret requiers 2 empty space above to function

### ISSUE THREAD

**Issue by citpo** [Poenjabiesous/OpenModularTurrets#36]
Hi,
Seems like the turret needs two empty block spaces above to function. 
Otherwise it stops targeting or fireing. Tried with Laser Turret and Machine Gun Turrent. Seems okay to cover the Turret Base. This also sees to affect placing Turrets below the Turret Base.

Version used is: OpenModularTurrets-1.7.10-1.3.2-24

/citpo

**Comment by mrgreaper** [comment]
ah, i had wondered why my base turrets just ignored the recent unwanted invasion of zombies lol
i believe im having the same issue

**Comment by Poenjabiesous** [comment]
Fixed in upcoming new release 1.4.1.
