### ISSUE TITLE
Feature Request: IGWMod support

### ISSUE THREAD

**Issue by Keridos** [Poenjabiesous/OpenModularTurrets#39]
Proposal: Add in support for the IGWMod. https://github.com/MineMaarten/IGW-mod
Provides ingame information for mods. I can get the framework for this from my own mod, and copy it in, then we just need to fill in the content for this mod.

- [x] basic support
- [x] more content

/edit:
I got the basic framework almost done, just a few minor things left to fix.

**Comment by Poenjabiesous** [comment]
Perfect. Heard about this before, looks really cool.

**Comment by Keridos** [comment]
I got it fully working now, we just need to add content.

**Comment by l3CY** [comment]
Could you add a config option to disable the IGW support notification on world startup.  Not everyone would like to use IGW so the continuous reminder is rather annoying.

**Comment by Keridos** [comment]
I will add that in in the next days.
