### ISSUE TITLE
Laser turret dont work on bottom

### ISSUE THREAD

**Issue by mentimjojo** [Poenjabiesous/OpenModularTurrets#40]
Hi guys,

Awesome what you guys do for this mod and thanks for making it. I have found a bug in multiplayer that when you add a laser turret on the bottom of a Resonant turret base it dont work. All the other sides are working. Can you look into this?

Many thanks :+1:

**Comment by Keridos** [comment]
Dont we check the line of sight from some modified coordinates?

**Comment by Poenjabiesous** [comment]
Replicate of #36, already fixed.
