### ISSUE TITLE
Remove CoFH Depedency

### ISSUE THREAD

**Issue by Keridos** [Poenjabiesous/OpenModularTurrets#41]
Why do we have the assets for some cofh stuff?

Request: Remove the dependency on CoFH stuff completely.

Need to to:
- [x] fix CoFHLib textures to use our own
- [x] check to see if it runs without CoFH Stuff

Of course we can keep the energy API.

**Comment by Poenjabiesous** [comment]
That's a good question. Will update the API on next push as well.

**Comment by Keridos** [comment]
I updated the RF API already. But not the rest yet.
