### ISSUE TITLE
Issue: Turrets and Leaves/Grass etc.

### ISSUE THREAD

**Issue by Keridos** [Poenjabiesous/OpenModularTurrets#43]
Maybe allow the turrets to shoot through these.

**Comment by Poenjabiesous** [comment]
In the new version, I allowed turret projectiles to destroy non-opaque blocks. Do you think we should just ignore the blocks completely?

**Comment by Keridos** [comment]
Destroying non opaque, no. But allow them to pass through those with the isAir() == true and no bounding boxes. That would apply for grass, torches etc.

**Comment by Poenjabiesous** [comment]
True, forgot about FMP.

**Comment by Poenjabiesous** [comment]
*Should* be fixed now.
