### ISSUE TITLE
Trusted players and server reboot

### ISSUE THREAD

**Issue by ceselegend** [Poenjabiesous/OpenModularTurrets#44]
It seems a server reboot erase the trusted player list from turrets.

**Comment by AtomicgermX69** [comment]
yes i can confirm this is happening on my server as well.......my server auto restarts 3 times a day most ppl are not using turrets  because of this issue..

**Comment by BarbasTheDog** [comment]
Can confirm. Turrets lose their trusted user list after a server restart. Leading to... rather amusing situations. :)
