### ISSUE TITLE
Server crash upon loading world

### ISSUE THREAD

**Issue by AnonymousPuppy** [Poenjabiesous/OpenModularTurrets#47]
I'm using a custom modpack, forge .1240, and OpenModularTurrets-1.7.10-1.3.2-24.jar. A player setup a turret on my server, and it ended up crashing the server. After restarting, the server kept crashing upon loading the world every time. I had to MCEdit the turrent out, and only then did the map load up. 

Here is the crash report: http://pastebin.com/Txdnf8KG

Please fix this ASAP, as this is a game-breaking bug. Thank you :)

**Comment by Poenjabiesous** [comment]
Same as #34. Fixed in new version. Please check closed tickets for similar problems before posting a new one, chances are if you are experiencing and issue you are not alone.

**Comment by AnonymousPuppy** [comment]
My bad, I only checked the open tickets, but I'll make sure to check closed ones as well next time. Looking forward to the upcoming version, so I can update my modpack :)

**Comment by Keridos** [comment]
I uploaded the new file to curseforge, my build server was down for 2 days, sorry for the delay. Should be available in a few minutes...
