### ISSUE TITLE
(major) Turrets wont attach to the turret base and suddenly dont own turret base.

### ISSUE THREAD

**Issue by mrgreaper** [Poenjabiesous/OpenModularTurrets#50]
Ok so if i place a turret base i can not shift click to place a turret on it, the turret breaks and drops instantly.

On server restart i can suddenly not open the gui of the turret base (works before the restart) i get a message telling me im not the owner of the turret

version : OpenModularTurrets-1.7.10-1.3.4-27
minecraft : 1.7.10
forge : 1277

**Comment by Keridos** [comment]
Do you use a cracked version of minecraft? If yes: Go buy the game...

**Comment by mrgreaper** [comment]
Then you have a rather nasty bug, hence the "major" tag and my slight confusion over the length of time at a reply, i had just figured it was something you guys knew about and were working on a fix for.

lets address the cracked version issue, the server has since been shut down as i ran out of money to pay for it, thats right it was a legit server on a paid host. my client is the feed the beast client, a third party mod pack i create and update (currently on hold due to the bug with open turrets and my reluctance to remove the mod, when it works its a great mod) 
I have been a minecraft player since alpha, and server admin (on and off) since just before the end of hmod. I have also dabled in modding (this is my github account so you should be able to see that too) 
I have not only brought minecraft but i have also donated to several mod developers over the years and assisted where i can (before my job took a nose dive wage wise and financialy screwed me)
Normally with my bug reports i would include logs etc which would of shown you i am an official paying minecrafter not a cracked user, however in this case there was no logs to help.
In no way have i ever used a cracked version! 

At the time of the server end i was getting issues with the turret bases losing owner (a good idea would be a creative item that allows for the removal of a turret base owned by any player) 
no one could place turrets on the bases and my official stance on it was "i have notified them, they know of the severity, im sure thier working on them" i had faith.

**Comment by Poenjabiesous** [comment]
Could not reproduce turret placement error. Make sure the turret you are trying to place is >/= the tier of base.
