### ISSUE TITLE
Lead for Bullets

### ISSUE THREAD

**Issue by Nicholai194** [Poenjabiesous/OpenModularTurrets#51]
I would like to see Lead become useable in place of Iron in the recipe for bullets

**Comment by Gambigobilla** [comment]
I agree, this is much logical considering real bullets have lead cores (excluding armor piercers) and this would add some new usage for less used lead resource.

**Comment by Keridos** [comment]
+1 for that

**Comment by Poenjabiesous** [comment]
Changed the Recipe to use lead now.
