### ISSUE TITLE
Feature Request: Advanced Trusted Players List

### ISSUE THREAD

**Issue by Disturbeddragon1** [Poenjabiesous/OpenModularTurrets#52]
Me and my husband were talking about this just the other day when we got to the point we could set up trusted players on our turrets, but what if there was an option for an advanced trusted players option so that you could allow others you trust to interact with your turret? They would be allowed to add/remove ammo, as well as change options on the turret and break/replace it anywhere, all while retaining the information that it belongs to the original owner like some mods do with their machines and such.

In the current version, there is a trusted players list but it only affects whether or not a turret will shoot players and does not give them the option to interact with it period unless they are the original owner. 

- [x] new GUI for that
- [x] TurretBase Class, including NBT Saving and loading
- [ ] test legacy compatability
- [x] implementing missing stuff in other classes regarding this.

**Comment by Keridos** [comment]
We might add 2 Lists for that one, one for administrating, the other for shooting.

**Comment by Keridos** [comment]
I will work on the non GUI stuff for this, ok @Poenjabiesous?
We can get rid of the trustedPlayers can change block config option then aswell.

**Comment by Poenjabiesous** [comment]
Yeah, we should.

What about an additional screen (accessed through a button on the base's GUI) that lists all trusted players, where the owner can tick boxes about what a specific trusted player may do (Perms). Options will include:

1. Open GUI
2. Change targeting params
3. Add trusted players
4. Drop base/turrets

**Comment by Keridos** [comment]
That sounds pretty good, maybe one more for editing permissions.

**Comment by Keridos** [comment]
I made it so that boolean for 4. is isAdmin. That one should basically make you able to drop the turret and change permissions.

**Comment by Poenjabiesous** [comment]
Phew. Done via 3142315d45cda45b0d9977a53fc5b094cfc4038f
