### ISSUE TITLE
Feature Request - Don't damage trusted players

### ISSUE THREAD

**Issue by DPxKnightxZero** [Poenjabiesous/OpenModularTurrets#55]
Alright so I have serious hang ups about turrets that kill their own on purpose on accident doesn't matter.

**Comment by Keridos** [comment]
??

**Comment by Poenjabiesous** [comment]
Dont understand the issue you are trying to explain.

**Comment by DPxKnightxZero** [comment]
I was wondering if the turrets could not affect owner of turret. I set up a turret wall and I got shot by turrets in crossfire.

**Comment by Keridos** [comment]
I think I know what you are trying to say, @Poenjabiesous we could implement a config option to disable that turrets affect their owner/trusted players. He means that if the turret shot another target and it hits the owner/trusted player it still deals damage.

**Comment by Poenjabiesous** [comment]
Got this one too...
