### ISSUE TITLE
a few issues i found while testing latest revision

### ISSUE THREAD

**Issue by nightstalker6669** [Poenjabiesous/OpenModularTurrets#58]
open modular turrets 1.3.8-35
forge 1343

i put this on my test server today and found a few problems.

first thing once a turret starts firing at a player, it doesn't stop when you add thier name to the whitelist.

whitelist doesn't seem to be working at all. when added to the whitelist and then turning on the turret to attack players, it still attacks players on the whitelist.

there doesn't seem to be any range cut off for any of the turrets anymore. i had a turret start shooting at me from pointblank range, and then moved away over 100 blocks and it will still shooting at me. this goes for all turret heads.

the armor penetration does work tho, and works great!

i want to add this mod to my PVP mod pack, so i'll be testing it intensively to help sort out all these bugs. I think you guys are on to an outstanding idea, and this is definitely something that was lacking in the world of modded PVP.

 if you need more input, please feel free to let me know.

**Comment by Keridos** [comment]
I will see about that targeting issue and the whitelist issue. Weird is that the whitelist should work. But maybe we have a smaller issue there. Targeting is still a bit weird for me. Would be better to check if a line of sight is given to the target before actually shooting.

**Comment by nightstalker6669** [comment]
was just checking in to see if there was anything i could test out on this mod, i have high hopes for this mod and eagerly wait for a good working version. if there is anything you need me to do let me know. i have multiple servers i can test this out on if you need feed back on something.

**Comment by Keridos** [comment]
Thanks for your help :)

**Comment by nightstalker6669** [comment]
your most welcome, i'm currently working on OpenComputers integration at the moment. I still have a lot to learn java wise, but its slowly going. i'm hoping to be able to control the turrets with computers soon. if you have anything that is already implimented (like just the basic drivers) i could probably work from there. i can get it to compile correctly right now, but just can't get the methods to work for some reason. but if you don't have anything, its cool. i'll eventually figure it out.

**Comment by Keridos** [comment]
Mh, did not really look how opencomputer drivers work until now. Might take a look at that soonish. Currently I am mostly working on my own mod (FloodLights) but when that is done I will get more active here.

**Comment by nightstalker6669** [comment]
yea it seems to still be outside my scope of understanding, but if i tinker with it enough i'll figure it out. just takes nothing but time.
