### ISSUE TITLE
Wooden Turret Base, lag server, lag proxy, crash

### ISSUE THREAD

**Issue by Yselith** [Poenjabiesous/OpenModularTurrets#60]
Hello,

I have a FTB Trident server on my network (using BungeeCord) and yesterday i got a memory leak problem and cpu usage from bungeecord process.

There was 1100 wooden turret bases on the base of a player, the TPS / MS was very good but players experienced a lot of lag. If the trident server was out of the bungeecord, memory leak was gone.

The players was receiving 600 Kbps from the server, we deleted all those blocks and it fixed our problems.

Mod version : OpenModularTurrets-1.7.10-1.3.4-27.jar

**Comment by Keridos** [comment]
We do not support other platforms than forge. If you can reproduce this issue in vanilla forge then this is valid.
