### ISSUE TITLE
(Request) Remove COFH dependency

### ISSUE THREAD

**Issue by assasing123** [Poenjabiesous/OpenModularTurrets#69]
Is there any chance you could create or make the mod not require Thermal Expansion and COFH (but keep the RF requirement)?

(in which case it would fallback to vanilla tier ingrediends, ex:
tier 1 wood
tier 2 iron
tier 3 gold
tier 4 diamond
tier 5 obsidian)

**Comment by Keridos** [comment]
Please read all the issues before creating a new one, this has already been requested. Thanks.
