### ISSUE TITLE
feature: on/off indicator in GUI.

### ISSUE THREAD

**Issue by nightstalker6669** [Poenjabiesous/OpenModularTurrets#70]
anyway you could implement an on/off indicator in the GUI? that way i could put a way for OC to turn on/off the turrets, and its reflected in the GUI. it would default on to keep the ability to switch it on and off with redstone, but then you can do something like setActive(true/false) to toggle it with OC. just an idea.

**Comment by Keridos** [comment]
Yes, and we could implement redstone control that way.

**Comment by nightstalker6669** [comment]
yep exactly what i was thinking.

**Comment by nightstalker6669** [comment]
or you could go one step further, and implement some sort of light (think LED) on one of the sides of the turret (or even on the turret head) to indicate weather the turret is currently enabled or disabled.

**Comment by Keridos** [comment]
Well, I do not think that would be desired by the PvP players...

**Comment by nightstalker6669** [comment]
true, or could be used as a deterrent for potential raiders. i was thinking more for the person setting up a perimeter, its easier to see a light on the turret, then to go to each turret just to verify that its active.

**Comment by Poenjabiesous** [comment]
I'll pick up this one as well, should be a quick fix.

**Comment by Keridos** [comment]
Erm, just a small offtopic question, I am a bit hesitant to start modifying stuff, or can we split up, I do the coding (TileEntities) for the changes, @Poenjabiesous you do graphics designing and the GUI stuff?

**Comment by nightstalker6669** [comment]
if you guys need any help with anything i'm more then happy to help (as i'm sure you noticed :D) i'm still in the learning stages of java, but am a quick learner. i'm not all that great on the graphics designing or GUI stuff, but coding for me is a ever growing passion.

**Comment by Keridos** [comment]
Btw: I am sitting in the #OpenModularTurrets channel on esperNet in IRC, if you wanna come chat a bit more direct.

**Comment by nightstalker6669** [comment]
yep i'm there.

**Comment by Poenjabiesous** [comment]
The gui stuff will be quick, I will basically just add a tickbox for "active". Just call me the Bob Ross of MS-paint

**Comment by Poenjabiesous** [comment]
After giving this some thought- as the turret bases already do imlement redstone control (for on/off), why would we need to add a switch in the GUI for control, when a lever will do the job? Maybe I'm missing something...

**Comment by nightstalker6669** [comment]
no an indicator as to weather it is currently on or off. for toggling with OC.

**Comment by Poenjabiesous** [comment]
So, you just need a flag inside the turretbase to see whether the base is currently on/off due to being powered by redstone?

**Comment by nightstalker6669** [comment]
yea, doesn't have to be anything special. like a green "ON" , red "OFF" then when i setActive(boolean) from OpenComputers, it'll toggle weather the turret is active or not.

**Comment by nightstalker6669** [comment]
its mainly for visual purposes, so people can just look into the turret base without having to go to a computer and getActive(boolean) to find out if a turret is switched on or off.

**Comment by Poenjabiesous** [comment]
Hmmm. That's different than what the base currently does. The base is currently in an on state when it is not being powered by redstone signal, and off when it is. a isActive() switch would be additional to the redstone check, and the two would not be mutually exclusive (due to current impl).

**Comment by Poenjabiesous** [comment]
Let me see what I can do.

**Comment by Poenjabiesous** [comment]
Yeah, this wont work. We will either have redstone control, or flag based control. We wont be able to do both.

**Comment by Poenjabiesous** [comment]
Cant you use redstone control to turn turrets on and off in OC? That's how most of the other mods with lua integration work?

**Comment by nightstalker6669** [comment]
you can, and thats not a problem. i'm in IRC.

**Comment by Keridos** [comment]
We can always have an inverted flag for redstone control, that is what I'd suggest.
