### ISSUE TITLE
Projectile won't penetrate non solid blocks such as grass block

### ISSUE THREAD

**Issue by tossaponk** [Poenjabiesous/OpenModularTurrets#74]
I don't know if this is intended, but I made the fix for it. With this code, it should allow projectile to penetrate non solid block. This code will also enable the turret to hit a target at point blank range instead of needing to wait at least 1 tick before projectile can hit an entity.

Implement code below on onImpact() function of various projectile.

if( movingobjectposition.typeOfHit == movingobjectposition.typeOfHit.BLOCK )
        {
            if (this.ticksExisted <= 1 )
            {
                // Prevent collision with self
                return;
            }

            Block hitBlock = worldObj.getBlock( movingobjectposition.blockX, movingobjectposition.blockY, movingobjectposition.blockZ );
            if( hitBlock != null && !hitBlock.getMaterial().isSolid() )
            {
                // Go through non solid block
                return;
            }
        }

**Comment by Keridos** [comment]
We just have one issue more: I think entities in blocks are not able to be hit that way?
