### ISSUE TITLE
Turret won't shoot diagonal target.

### ISSUE THREAD

**Issue by tossaponk** [Poenjabiesous/OpenModularTurrets#78]
This bug is due to target detection method using all entities within an area which is using a cube for detection at this line
https://github.com/Poenjabiesous/OpenModularTurrets/blob/edd36c56ee2f745cb246405785b81d5685d10686/src/main/java/openmodularturrets/tileentity/turrets/TurretHeadUtils.java#L70

Then turret immediately disengage target due to distance check is checking by using Euclidean distance from this line
https://github.com/Poenjabiesous/OpenModularTurrets/blob/edd36c56ee2f745cb246405785b81d5685d10686/src/main/java/openmodularturrets/tileentity/turrets/TurretHead.java#L233

Sometime this loop will continue until the target despawns or walks out of the detection cube thus making turret fail to attack its target or acquiring a new target.

This can be fixed by using this code (Making this algorithm into a function is recommended for cleaner code.)
```
if ( MathHelper.abs_max( MathHelper.abs_max( target.posX - this.xCoord, target.posY - this.yCoord ), target.posZ - this.zCoord ) > (getTurretRange() + TurretHeadUtils.getRangeUpgrades(base)))
```
The above line will calculate distance in Chebyshev distance which is the same method that is being used to pick the potential target.

**Comment by Poenjabiesous** [comment]
This is a very valid argument. Thanks for pointing it out! Will you be able to push the changes, or should I replace the line with the proposed code?

Thanks for the help.

**Comment by Keridos** [comment]
I manually merged his ideas. But if you want, we are open to pull-requests, @tossaponk.

**Comment by tossaponk** [comment]
Due to the fact that I'm fixing the bug myself so that apply to other mods too, and that make my source folder very messy so I cannot make a pull request directly without proper repository clone. So I would like you guys to implement those for me.

**Comment by Keridos** [comment]
Ok, thanks for the submission then, we will implement this.
