### ISSUE TITLE
Turret keep shooting a non existence target.

### ISSUE THREAD

**Issue by tossaponk** [Poenjabiesous/OpenModularTurrets#83]
Sometime, an entity is being removed from the world without being killed and turret keep shooting at it since isDead is still false but it is no longer exists in the world.

This can be fixed by doing one more check for entity existence before shooting it.

Change these lines
https://github.com/Poenjabiesous/OpenModularTurrets/blob/7f82e3802156d4c0c66adc8343182b45da158293/src/main/java/openmodularturrets/tileentity/turrets/TurretHead.java#L212-215

To this
```
            // is there a target, and Has it died in the previous tick?
            if (target == null || target.isDead || this.getWorldObj().getEntityByID(target.getEntityId()) == null) {
                target = getTarget();
            }
```

**Comment by Poenjabiesous** [comment]
Fixed. Thanks!
