### ISSUE TITLE
Turret projectile jerky movement and rendering distance problem

### ISSUE THREAD

**Issue by tossaponk** [Poenjabiesous/OpenModularTurrets#85]
Projectile is updating itself every tick causing irregular movement because of client-server latency. Since most type of projectile(Except rocket) do not change their trajectory mid-flight, we can safely change their updating frequency to 20 tick(1 sec) without any impact and reduce network bandwidth usage for projectile update packets. This will also fix the movement problem since client can calculate projectile displacement by themselves without needing the position sync packet. As a result, we can increase projectile tracking distance making the state of turret visible from farther away(From 16 to 64 blocks for example).

Change these lines
https://github.com/Poenjabiesous/OpenModularTurrets/blob/master/src/main/java/openmodularturrets/handler/ProjectileEntityHandler.java#L14-21

To this for an example
```
		EntityRegistry.registerModEntity(RocketProjectile.class,
				"rocketProjectile", 1, turrets, 16, 1, true);
		EntityRegistry.registerModEntity(GrenadeProjectile.class,
				"grenadeProjectile", 2, turrets, 64, 20, true);
		EntityRegistry.registerModEntity(BulletProjectile.class,
				"bulletProjectile", 3, turrets, 64, 20, true);
		EntityRegistry.registerModEntity(LaserProjectile.class,
				"laserProjectile", 4, turrets, 64, 20, true);
```

Also, one more thing is needed to be done to actually increase projectile rendering distance.
Override these methods to change default rendering distance. The below example is set to infinite distance as long as the projectile is still live on the client side.
```
@Override
    public boolean isInRangeToRenderDist(double p_70112_1_) {
        return true;
    }

    @Override
    public boolean isInRangeToRender3d(double p_145770_1_, double p_145770_3_, double p_145770_5_) {
        return true;
    }
```
^ These method should be implement in class TurretProjectile if they share the same rendering distance rule, Otherwise, Implement them separately in their respective class.

**Comment by Poenjabiesous** [comment]
Thanks again.
