### ISSUE TITLE
More targeting optimization

### ISSUE THREAD

**Issue by tossaponk** [Poenjabiesous/OpenModularTurrets#90]
Current target selection will select all entities in range, including items and tile entities. Change the target selection from Entity.class to EntityLivingBase.class might be a better alternative.

https://github.com/Poenjabiesous/OpenModularTurrets/blob/master/src/main/java/openmodularturrets/util/TurretHeadUtils.java#L72

**Comment by Keridos** [comment]
Thanks again!
