### ISSUE TITLE
Waila Integration

### ISSUE THREAD

**Issue by Keridos** [Poenjabiesous/OpenModularTurrets#93]
I can add in Waila Integration if you think that is a good idea, just answer here and I will implement that.

**Comment by Poenjabiesous** [comment]
I think this is an absolute must for any new/updated mod. Let me know if I can help in any way.

**Comment by Keridos** [comment]
Just a small brainstorm which info should be displayed on the tooltip would be enough. This is pretty much copy paste from an example class and then adding like a few lines of code.

**Comment by Poenjabiesous** [comment]
Turrets:
-Name
Not much else to do there, as far as I can think right now.

Base: 
-Power
-isActive  
-Owner
