### ISSUE TITLE
Sounds very loud

### ISSUE THREAD

**Issue by Keridos** [Poenjabiesous/OpenModularTurrets#94]
I personally find the sounds the turrets make too loud, maybe decrease their volume by 50-75%?

**Comment by Poenjabiesous** [comment]
Agreed.

**Comment by cyris69** [comment]
Since it appears this has never been done here is my ogg files tones down to acceptable levels. Just go into the jar file like you would a zip file, remove the ogg files in it and add these. use 7z which will let you drag and drop ect. http://www.mediafire.com/view/k9d1j8kf6xa5ht1/OMT_Sounds.zip
