### ISSUE TITLE
Turret projectile saving to unloaded chunks cause server to freeze

### ISSUE THREAD

**Issue by tossaponk** [Poenjabiesous/OpenModularTurrets#97]
I'm having a problem with projectile getting saved to chunk entity data. At first glance, nothing seems to be an issue. But there's a case where turret is shooting at a target near the unloaded chunk and miss, causing its projectile to travel into an unloaded chunk. In my case, according to Opis, more than 8000  instances got saved in a chunk, and when that chunk is loading, server will froze up and overloaded due to too many projectile is being updated.

Is it really necessary to save the projectile entity at all? Could we discard it as it travels into an unloaded chunk? Since it's already missed its target anyway.

**Comment by Poenjabiesous** [comment]
Hi Tossaponk

To be quite honest, I wasn't even aware that we were saving projectile entity data. I was under the impression that all projectile date was discarded as it leaves loaded chunks.

**Comment by tossaponk** [comment]
Oh I see, then I'll have to tell you that there's an option to tell the world to not save an entity. By default, all classes which extend Entity will save their content when chunk is being unloaded.

Here's what I found
```
    /**
     * Either write this entity to the NBT tag given and return true, or return false without doing anything. If this
     * returns false the entity is not saved on disk. Ridden entities return false here as they are saved with their
     * rider.
     */
    public boolean writeToNBTOptional(NBTTagCompound p_70039_1_)
    {
        String s = this.getEntityString();

        if (!this.isDead && s != null && this.riddenByEntity == null)
        {
            p_70039_1_.setString("id", s);
            this.writeToNBT(p_70039_1_);
            return true;
        }
        else
        {
            return false;
        }
    }
```
According to the document, I think override this method and return false will tell the world that this entity should not be saved to disk.

**Comment by Keridos** [comment]
Yeah that is a nasty bug atm.

**Comment by Poenjabiesous** [comment]
Last fix *might* solve the problem. I saw that there were readFromNBT and writeToNBT methods overridden in the base projectile class, Since we don't need to manually update projectiles, I removed those two methods and implemented @tossaponk's suggested fix.
